defaults: # for loading the default config
  - task: segmentation # ??? Task performed (segmentation, classification etc...)
    optional: True
  - model_type: pointnet2 # ??? Type of model to use, e.g. pointnet2, rsconv etc...
    optional: True
  - dataset: nexplore-fixed # ???
    optional: True

  - visualization: default
  - lr_scheduler: exponential
  - training: default

  - debugging: default.yaml
  - models: ${defaults.0.task}/${defaults.1.model_type}
  - data: ${defaults.0.task}/${defaults.2.dataset}
  - sota # Contains current SOTA results on different datasets (extracted from papers !).
  - hydra/job_logging: custom
  - hydra/output: custom  # add the support for user-defined experiment folder (where to save the experiment files)

job_name: benchmark # prefix name for saving the experiment file.
model_name: pointnet2_largemsg # ??? Name of the specific model to load
update_lr_scheduler_on: "on_epoch" # ["on_epoch", "on_num_batch", "on_num_sample"]
selection_stage: ""
pretty_print: True
eval_frequency: 1

no_train: False # set to True to skip training and only preprocess

tracker_options: # Extra options for the tracker
  full_res: False
  make_submission: False
  track_boxes: False

