num_workers: 0
batch_size: 1
cuda: 1
weight_name: "miou" # Used during resume, select with model to load from [miou, macc, acc..., latest] ['latest', 'best_loss_seg', 'best_acc', 'best_macc', 'best_miou']
enable_cudnn: True
checkpoint_dir: "C:/Users/mpautzke/Data/models/Baselines/KpConv"
model_name: "KPConvPaper" #TOTO
enable_dropout: False
process_full_resolution: True
output_path: "C:/Users/mpautzke/Data/output" # Where the output goes
input_path: "C:/Users/mpautzke/Data/points3d/nexplores3disfused/raw/taktkeller/segment_2"
input_filename: "segment_2.txt"
confidence_threshold: 0.0 #all under this confidence are changed to 0

# Dataset specific
defaults:
  - dataset: nexplore
    optional: true

