num_workers: 0
batch_size: 1
cuda: 1
weight_name: "miou" # Used during resume, select with model to load from [miou, macc, acc..., latest]
enable_cudnn: True
checkpoint_dir: "C:/Users/mpautzke/Data/models/Baselines/KpConv/550epochs/benchmark-KPConvPaper-20210627_131435"
model_name: "KPConvPaper" #TOTO
enable_dropout: False
process_full_resolution: True
output_path: "C:/Users/mpautzke/Data/output" # Where the output goes
input_path: "C:/Users/mpautzke/Data/points3d/nexplores3disfused/raw/tule/segment_2"
input_filename: "segment_2.txt"

# Dataset specific
defaults:
  - dataset: nexplore
    optional: true

